# Generated by Django 5.2.11 on 2026-02-25 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WallSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='段落名称')),
                ('location', models.CharField(max_length=200, verbose_name='地理位置')),
                ('built_year', models.CharField(max_length=50, verbose_name='建造年代')),
                ('length', models.CharField(max_length=50, verbose_name='长度')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('image', models.ImageField(blank=True, upload_to='wall_images/', verbose_name='图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '城墙段落',
                'verbose_name_plural': '城墙段落',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='事件标题')),
                ('year', models.CharField(max_length=20, verbose_name='发生年份')),
                ('description', models.TextField(verbose_name='事件描述')),
                ('wall_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wall_app.wallsection', verbose_name='相关城墙段落')),
            ],
            options={
                'verbose_name': '历史事件',
                'verbose_name_plural': '历史事件',
            },
        ),
    ]
