# Generated by Django 5.2.11 on 2026-02-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_contribution_usercontribution_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallsection',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/梅花头像.jpg', verbose_name='图片'),
        ),
    ]
