# Generated by Django 5.2.11 on 2026-02-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0004_contribution_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontribution',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='地址'),
        ),
    ]
