# Generated by Django 5.2.11 on 2026-02-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0005_usercontribution_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='title',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='user',
        ),
        migrations.AddField(
            model_name='usercontribution',
            name='length',
            field=models.CharField(blank=True, max_length=50, verbose_name='长度'),
        ),
    ]
