# Generated by Django 5.2.11 on 2026-02-28 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0006_remove_contribution_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercontribution',
            options={'verbose_name': '用户贡献', 'verbose_name_plural': '用户贡献'},
        ),
        migrations.RemoveField(
            model_name='usercontribution',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usercontribution',
            name='content',
        ),
        migrations.RemoveField(
            model_name='usercontribution',
            name='title',
        ),
        migrations.AddField(
            model_name='usercontribution',
            name='built_year',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='建造年代'),
        ),
        migrations.AddField(
            model_name='usercontribution',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='详细描述'),
        ),
        migrations.AddField(
            model_name='usercontribution',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='地理位置'),
        ),
        migrations.AddField(
            model_name='usercontribution',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='段落名称'),
        ),
        migrations.AlterField(
            model_name='usercontribution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='usercontribution',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='usercontribution',
            name='length',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='长度'),
        ),
        migrations.AlterField(
            model_name='usercontribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='贡献者'),
        ),
        migrations.AlterField(
            model_name='wallsection',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/', verbose_name='图片'),
        ),
    ]
