# Generated by Django 5.2.11 on 2026-03-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0008_wallsection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallsection',
            name='event',
            field=models.TextField(blank=True, null=True, verbose_name='相关历史事件'),
        ),
    ]
